[build]
  functions = "functions"
  command = "netlify-lambda install && mkdir ./public"
[template.environment]
  AURA_CONNECTION_URI = "AuraDB connection URI"
  AURA_USER = "AuraDB username"
  AURA_PASSWORD = "AuraDB password"
  TELEGRAM_BOT_TOKEN = "Telegram bot token here"
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
